### ISSUE TITLE
Text input support

### ISSUE THREAD

**Issue by junekiwi** [JoelCapitao/NetScriptGen#1]
Hi,
Nice work, sounds perfect for working with large configuration files.

I think it would be nice to be able (in addition to XLSX) to use text files as an input for variables and sub-templates.
This would allow quick editing with text editors, and pre-processing or even generation of the input data by other tools (i.e. a network scanner).

XML or JSON are probably too verbose, but YAML may be a good fit:

``` yaml
switches:
    - hostname: SW1
      location: TR01
      layer:    access
# [...]
vlans:
    - id:   101
      name: VLAN-DATA-01
      net:  10.1.1.0
      mask: 255.255.255.0

subTemplate:  >
    vtp version {version} 
    vtp domain {domain}
    vtp password {password}
    vtp mode {mode}
```

I may do a POC when I have some time :grinning:
